import {
  Company,
  Member,
  Project,
  ProjectMember,
  Stakeholder,
  OnboardingLog,
} from "./types";

export const mockCompany: Company = {
  id: "c1",
  name: "V4 Rokko",
  cnpj: "12.345.678/0001-90",
  address: "Av. Paulista, 1000 - São Paulo, SP",
  phone: "5511999999999",
};

export const mockMembers: Member[] = [
  {
    id: "m1",
    name: "Ruston",
    nickname: "Ruston",
    email: "ruston@v4company.com",
    phone: "5511911111111",
    role: "owner",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ruston",
  },
  {
    id: "m2",
    name: "Tiago Bardini",
    nickname: "Tiago",
    email: "tiago@v4company.com",
    phone: "5511922222222",
    role: "coord_geral",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tiago",
  },
  {
    id: "m3",
    name: "Ana Silva",
    nickname: "Ana",
    email: "ana@v4company.com",
    phone: "5511933333333",
    role: "coord_equipe",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
  },
  {
    id: "m4",
    name: "Carlos Santos",
    nickname: "Carlos",
    email: "carlos@v4company.com",
    phone: "5511944444444",
    role: "coord_equipe",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
  },
  {
    id: "m5",
    name: "Bia Costa",
    nickname: "Bia",
    email: "bia@v4company.com",
    phone: "5511955555555",
    role: "comercial",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bia",
  },

  {
    id: "m10",
    name: "Roberto Carlos",
    nickname: "Beto",
    email: "roberto@v4company.com",
    phone: "5511910101010",
    role: "gestor_projetos",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Beto",
  },
  {
    id: "m11",
    name: "Juliana Paes",
    nickname: "Ju",
    email: "juliana@v4company.com",
    phone: "5511911111112",
    role: "gestor_projetos",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ju",
  },
  {
    id: "m7",
    name: "Mariana Lima",
    nickname: "Mari",
    email: "mari@v4company.com",
    phone: "5511977777777",
    role: "designer",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mari",
  },
  {
    id: "m7b",
    name: "Felipe Neto",
    nickname: "Felipe",
    email: "felipe@v4company.com",
    phone: "5511977777778",
    role: "designer",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felipe",
  },
  {
    id: "m8",
    name: "Pedro Alves",
    nickname: "Pedro",
    email: "pedro@v4company.com",
    phone: "5511988888888",
    role: "gestor_trafego",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pedro",
  },
  {
    id: "m8b",
    name: "Camila Pitanga",
    nickname: "Camila",
    email: "camila@v4company.com",
    phone: "5511988888889",
    role: "gestor_trafego",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Camila",
  },
  {
    id: "m9",
    name: "Lucas Rocha",
    nickname: "Lucas",
    email: "lucas@v4company.com",
    phone: "5511999999999",
    role: "copywriter",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
  },
  {
    id: "m9b",
    name: "Bruna Marquezine",
    nickname: "Bruna",
    email: "bruna@v4company.com",
    phone: "5511999999998",
    role: "copywriter",
    isActive: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bruna",
  },
];

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "Power Bikes — Byline + EE",
    clientName: "Power Bikes",
    clientPhone: "5511900000001",
    kommoLeadId: "1001",
    kommoLink: "https://v4.kommo.com/leads/1001",
    product: ["byline", "ee"],
    contractValue: 5000,
    projectStartDate: new Date().toISOString().split("T")[0],
    stage: "aguardando_comercial",
    welcomeSent: false,
    createdAt: threeDaysAgo.toISOString(),
    updatedAt: threeDaysAgo.toISOString(),
  },
  {
    id: "p2",
    name: "Tech Solutions",
    clientName: "Tech Solutions",
    clientPhone: "5511900000002",
    kommoLeadId: "1002",
    kommoLink: "https://v4.kommo.com/leads/1002",
    product: [],
    contractValue: 8000,
    projectStartDate: new Date().toISOString().split("T")[0],
    stage: "atribuir_coordenador",
    welcomeSent: false,
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
  },
  {
    id: "p3",
    name: "Padaria Doce Pão",
    clientName: "Padaria Doce Pão",
    clientPhone: "5511900000003",
    kommoLeadId: "1003",
    kommoLink: "https://v4.kommo.com/leads/1003",
    product: [],
    contractValue: 3000,
    projectStartDate: new Date().toISOString().split("T")[0],
    assignedCoordinatorId: "m3", // Ana
    assignedById: "m2", // Tiago
    stage: "atribuir_equipe",
    welcomeSent: false,
    createdAt: threeDaysAgo.toISOString(),
    updatedAt: yesterday.toISOString(),
  },
  {
    id: "p4",
    name: "Clinica Sorriso — Byline",
    clientName: "Clinica Sorriso",
    clientPhone: "5511900000004",
    kommoLeadId: "1004",
    kommoLink: "https://v4.kommo.com/leads/1004",
    product: ["byline"],
    contractValue: 4500,
    projectStartDate: new Date().toISOString().split("T")[0],
    assignedCoordinatorId: "m4", // Carlos
    assignedById: "m2",
    stage: "criar_workspace",
    welcomeSent: false,
    createdAt: threeDaysAgo.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "p5",
    name: "Imobiliária Casa Nova — EE",
    clientName: "Imobiliária Casa Nova",
    clientPhone: "5511900000005",
    kommoLeadId: "1005",
    kommoLink: "https://v4.kommo.com/leads/1005",
    product: ["ee"],
    contractValue: 6000,
    projectStartDate: new Date().toISOString().split("T")[0],
    assignedCoordinatorId: "m3", // Ana
    assignedById: "m2",
    gchatSpaceId: "spaces/123",
    wppGroupId: "123@g.us",
    gdriveFolderId: "folder123",
    gdriveFolderLink: "https://drive.google.com/drive/folders/folder123",
    ekyteId: "ekyte123",
    workspaceStatus: {
      gchat: "created",
      whatsapp: "created",
      gdrive: "created",
      ekyte: "created",
    },
    stage: "boas_vindas",
    welcomeSent: false,
    createdAt: threeDaysAgo.toISOString(),
    updatedAt: now.toISOString(),
  },
];

export const mockProjectMembers: ProjectMember[] = [
  { id: "pm1", projectId: "p4", memberId: "m4", roleInProject: "coord_equipe" },
  { id: "pm3", projectId: "p4", memberId: "m7", roleInProject: "designer" },
  {
    id: "pm4",
    projectId: "p4",
    memberId: "m8",
    roleInProject: "gestor_trafego",
  },
  { id: "pm5", projectId: "p4", memberId: "m9", roleInProject: "copywriter" },
];

export const mockStakeholders: Stakeholder[] = [
  {
    id: "s1",
    projectId: "p1",
    name: "João Silva",
    phone: "5511900000001",
    email: "joao@powerbikes.com",
    role: "CEO",
  },
  {
    id: "s2",
    projectId: "p2",
    name: "Maria Souza",
    phone: "5511900000002",
    email: "maria@techsolutions.com",
    role: "Marketing Manager",
  },
];

export const mockLogs: OnboardingLog[] = [
  {
    id: "l1",
    projectId: "p1",
    action: "stage_changed",
    details: { from: null, to: "aguardando_comercial" },
    createdAt: threeDaysAgo.toISOString(),
  },
  {
    id: "l2",
    projectId: "p2",
    action: "stage_changed",
    details: { from: "aguardando_comercial", to: "atribuir_coordenador" },
    performedBy: "m5",
    createdAt: yesterday.toISOString(),
  },
];
